language: csharp
install:
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | sh
  - source ~/.dnx/dnvm/dnvm.sh
  - dnvm upgrade
script:
  - bash build.sh
mono:
  - nightly
notifications:
  email: false
